version: '3.8'

services:
  app:
    image: node:20-bookworm

    volumes:
      - ..:/workspaces/decarrerita:cached

    working_dir: /workspaces/decarrerita

    command: sleep infinity

    ports:
      - "3000:3000"

    depends_on:
      - db

    environment:
      DATABASE_URL: "postgresql://decarrerita:decarrerita_dev@db:5432/decarrerita_db?schema=public"

  db:
    image: postgres:16

    restart: always

    environment:
      POSTGRES_USER: decarrerita
      POSTGRES_PASSWORD: decarrerita_dev
      POSTGRES_DB: decarrerita_db

    ports:
      - "5432:5432"